# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true

      - run: npm install
      - run: npm run build

      - name: Publish
        uses: pascalgn/npm-publish-action@v1.3.3
        with: # All of theses inputs are optional
          tag_name: 'v%s'
          tag_message: 'v%s'
          commit_pattern: "^Release (\\S+)"
          workspace: '.'
        env: # More info about the environment variables in the README
          GITHUB_TOKEN: ${{ secrets.TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # You need to set this in your repo settings
